apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  APP_ENV: "development"
  LOG_LEVEL: "info"
  API_URL: "http://user-service:8080"
  DATABASE_URL: "postgres://postgres:postgres@host.docker.internal:5432/usersdb?sslmode=disable"
  PORT: "8080"
