apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
stringData:
  database-url: "postgres://postgres:postgres@postgres:5432/usersdb?sslmode=disable"
  jwt-secret: ${JWT_SECRET}
  access-token-ttl: ${ACCESS_TOKEN_TTL}
  refresh-token-ttl: ${REFRESH_TOKEN_TTL}
  google-client-id: ${GOOGLE_CLIENT_ID}
  google-client-secret: ${GOOGLE_CLIENT_SECRET}
  google-redirect-uri: ${GOOGLE_REDIRECT_URI}